### ISSUE TITLE
Bug in PCB rev1 // TODO for PCB rev2

### ISSUE THREAD

**Issue by rleh** [roboterclubaachen/micro-motor#1]
* [ ] SPI MISO pull-up resistor (10k)
* [ ] ~I²C pull-up resistors (4k7)~
* [ ] Analog (NTC) temperature sensor instead of I²C
* [ ] Measure (ADC) or detect (GPIO) the input voltage from STM32
* [ ] Remove integrated magnet encoder
* [ ] ~THT terminals~ Small SMD connectors (e.g. [JST GH](https://jst.de/product-family/show/89/gh))
  * [ ] Encoder (A, B, I, GND, 5V|3.3V)
  * [ ] Hall sensor (U, V, W, GND, 5V|3.3V)
  * [ ] End switch
  * [ ] CAN?
* [ ] Power connectors (e.g. [JST XH](https://jst.de/product-family/show/184/xh))
  * [ ]  Power supply: 20V, 6V, GND; >=5A
  * [ ] Combined with CAN?
* [ ] Use MOSFET R_dson (4..6mΩ) instead of 5mΩ shunt resistor?
* [ ] NCP4623 is *NRND* -> Replacement: [ADP7112](http://www.analog.com/media/en/technical-documentation/data-sheets/ADP7112.pdf) *1mm × 1.2mm, 6-ball WLCSP*
  * [ ] Discussion: [Fully integrated switching regulator TPS82150](http://www.ti.com/product/TPS82150) for 5V (and 3.3V)?
* [ ] Mechanical dimensions: ~Round~ Rectangular shape, approx. 15x25mm²

To be continued...

**Comment by rleh** [comment]
Done.
